create database xhb;
use xhb;
CREATE TABLE TAIKHOAN(
    ID int not null primary key auto_increment,
    usename varchar(55) not null,
    password varchar(55) not null
);
INSERT INTO TAIKHOAN(usename, password) VALUES('HoangCongLap', '123');
INSERT INTO TAIKHOAN(usename, password) VALUES('L', '1');
INSERT INTO TAIKHOAN(usename, password) VALUES('La', '12');

CREATE TABLE SINHVIEN(
	IDMSSV varchar(55) not null primary key,
    NAME varchar(55) not null,
	GENDER varchar(5),
	BRITHDATE date,
	OVERALLSCORE float,
	FAMILYSITUATION varchar(100)
);
select * from SINHVIEN;
INSERT INTO SINHVIEN(IDMSSV, NAME, GENDER, BRITHDATE, OVERALLSCORE, FAMILYSITUATION) VALUES('205051944','HoangCongLap', 'nam','2002-04-12','5','kha');
INSERT INTO SINHVIEN(IDMSSV, NAME, GENDER, BRITHDATE, OVERALLSCORE, FAMILYSITUATION) VALUES('205051945','congduc', 'nam','2005-06-11','7','ngheo');
INSERT INTO SINHVIEN(IDMSSV, NAME, GENDER, BRITHDATE, OVERALLSCORE, FAMILYSITUATION) VALUES('205051946','sang', 'nam','2009-12-22','8','giau');
INSERT INTO SINHVIEN(IDMSSV, NAME, GENDER, BRITHDATE, OVERALLSCORE, FAMILYSITUATION) VALUES('205051947','huynhnhu', 'nu','2001-01-01','9','kha');
INSERT INTO SINHVIEN(IDMSSV, NAME, GENDER, BRITHDATE, OVERALLSCORE, FAMILYSITUATION) VALUES('205051948','huyhoang', 'nam','2009-06-29','10','ngheo');
INSERT INTO SINHVIEN(IDMSSV, NAME, GENDER, BRITHDATE, OVERALLSCORE, FAMILYSITUATION) VALUES('205051949','duynhat', 'nam','2007-10-22','8','giau');
INSERT INTO SINHVIEN(IDMSSV, NAME, GENDER, BRITHDATE, OVERALLSCORE, FAMILYSITUATION) VALUES('205051950','suri', 'nu','2000-09-01','3','kha');
INSERT INTO SINHVIEN(IDMSSV, NAME, GENDER, BRITHDATE, OVERALLSCORE, FAMILYSITUATION) VALUES('205051990','dat', 'nam','2023-09-01','10','kha');
CREATE TABLE TOCHUC(
    ID varchar(55) not null primary key,
	TENTOCHUC varchar(100)
);
select * from TOCHUC;
INSERT INTO TOCHUC(ID, TENTOCHUC) VALUES('01A','ABC');
INSERT INTO TOCHUC(ID, TENTOCHUC) VALUES('02B','NamABank');
INSERT INTO TOCHUC(ID, TENTOCHUC) VALUES('03C','UEF');
INSERT INTO TOCHUC(ID, TENTOCHUC) VALUES('04D','Vietcombank');
INSERT INTO TOCHUC(ID, TENTOCHUC) VALUES('05E','');
CREATE TABLE THONGTINHOCBONG(
    IDHocBong varchar(55) not null primary key,
    IDSinhVien varchar(55) ,
    IDToChuc varchar(55),
	NGAYNHAN date,
	SOTIEN INT
);
select * from THONGTINHOCBONG;
INSERT INTO THONGTINHOCBONG(IDHocBong,IDSinhVien,IDToChuc, NGAYNHAN, SOTIEN) VALUES('111','205051944','01A','2019-01-01','1000000');
INSERT INTO THONGTINHOCBONG(IDHocBong,IDSinhVien,IDToChuc, NGAYNHAN, SOTIEN) VALUES('222','205051945','02B','2019-10-20','3000000');
INSERT INTO THONGTINHOCBONG(IDHocBong,IDSinhVien,IDToChuc, NGAYNHAN, SOTIEN) VALUES('333','205051947','03C','2022-03-01','4000000');
INSERT INTO THONGTINHOCBONG(IDHocBong,IDSinhVien,IDToChuc, NGAYNHAN, SOTIEN) VALUES('444','205051950','04D','2023-01-027','2000000');




alter table THONGTINHOCBONG add constraint FK_THONGTINHOCBONG_TOCHUC foreign key(IDToChuc) references TOCHUC(ID);
alter table THONGTINHOCBONG add constraint FK_THONGTINHOCBONG_SINHVIEN foreign key(IDSinhVien) references SINHVIEN(IDMSSV);



SELECT SINHVIEN.IDMSSV, SINHVIEN.NAME, SINHVIEN.GENDER, SINHVIEN.BRITHDATE, SINHVIEN.OVERALLSCORE, SINHVIEN.FAMILYSITUATION,THONGTINHOCBONG.IDHocBong, THONGTINHOCBONG.NGAYNHAN, THONGTINHOCBONG.SOTIEN,TOCHUC.TENTOCHUC
FROM THONGTINHOCBONG
 JOIN TOCHUC ON THONGTINHOCBONG.IDToChuc=TOCHUC.ID
 JOIN SINHVIEN ON THONGTINHOCBONG.IDSinhVien=SINHVIEN.IDMSSV;
 
SELECT SINHVIEN.IDMSSV, SINHVIEN.NAME, SINHVIEN.GENDER, SINHVIEN.BRITHDATE, SINHVIEN.OVERALLSCORE, SINHVIEN.FAMILYSITUATION,THONGTINHOCBONG.IDHocBong, THONGTINHOCBONG.NGAYNHAN, THONGTINHOCBONG.SOTIEN,TOCHUC.TENTOCHUC
FROM  SINHVIEN
 left JOIN THONGTINHOCBONG ON THONGTINHOCBONG.IDSinhVien=SINHVIEN.IDMSSV
 left JOIN TOCHUC ON THONGTINHOCBONG.IDToChuc=TOCHUC.ID
 where THONGTINHOCBONG.NGAYNHAN <='2023-03-29' and  THONGTINHOCBONG.SOTIEN is not null and TOCHUC.TENTOCHUC is not null;
 
UPDATE THONGTINHOCBONG
SET NGAYNHAN = '2020-01-01', SOTIEN= '2000000'
WHERE IDHocBong = '111';